In [1]:
import pandas as pd

Una ***pivot table*** es una herramienta para resumir y reorganizar columnas de un DataFrame de pandas, que además permite crear cálculos estadísticos (suma, conteos, promedios, etc.).

Básicamente transforma los valores de determinadas filas o columnas en indices de un nuevo DataFrame, la intersección de éstos es el valor resultante.

La nueva organización de los datos nos ayuda a encontrar patrones que pudieran estar ocultos en los datos crudos.

**Función:**

***pivot_table()***: Puede implementarse directo del DataFrame o a partir de la librería en si misma "pd.pivot_table()" con la diferencia de que ésta última recibe el DF como parámetro.

Parámetros:

- data: Cuando se utiliza la función directamente de pandas.

- values: Nombre de la columna o columnas (lista) que rellenarán la tabla a partir de la función de agregación.

- index: Nombre de la columna donde se tomarán los valores para crear los indices del DataFrame resultante.

- columns: Nombre de la columna donde se tomarán los valores las nuevas columnas del DataFrame resultante.

- aggfunc: Función de agregación a aplicar

In [9]:
sales_data = pd.read_csv('online_retail.csv', encoding='latin1')

In [8]:
pivot_table = pd.pivot_table(sales_data, values='Quantity', index='Country',
                             columns='StockCode', aggfunc='sum')
pivot_table

StockCode,10002,10080,10120,10123C,10123G,10124A,10124G,10125,10133,10134,...,M,PADS,POST,S,gift_0001_10,gift_0001_20,gift_0001_30,gift_0001_40,gift_0001_50,m
Country,,,,,,,,,,,,,,,,,,,,,
Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,272.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Channel Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cyprus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Czech Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Denmark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EIRE,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,NaN,...,-2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
European Community,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Finland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,89.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,372.0,NaN,10.0,NaN,NaN,NaN,NaN,470.0,NaN,NaN,...,-16.0,NaN,803.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Germany,1.0,NaN,NaN,NaN,NaN,NaN,NaN,120.0,NaN,NaN,...,2.0,NaN,1104.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Greece,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hong Kong,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Iceland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Israel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Italy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.0,NaN,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Japan,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lebanon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lithuania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Malta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Netherlands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-480.0,NaN,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Norway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,57.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Portugal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,...,1.0,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Saudi Arabia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Singapore,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Spain,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.0,NaN,209.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sweden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Switzerland,12.0,NaN,NaN,NaN,NaN,NaN,NaN,20.0,10.0,NaN,...,NaN,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United Kingdom,615.0,495.0,183.0,-13.0,-38.0,16.0,17.0,686.0,2645.0,-19.0,...,3662.0,4.0,3328.0,-59.0,39.0,20.0,37.0,3.0,4.0,1.0
Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Apilar y desapilar información:

In [11]:
df = pd.DataFrame({
    'A': ['foo', 'bar', 'baz'],
    'B': [1, 2, 3],
    'C': [4, 5, 6]
    })

df

     A  B  C
0  foo  1  4
1  bar  2  5
2  baz  3  6

Apilamos el dataframe:

In [12]:
df_stack = df.stack()
df_stack

0  A    foo
   B      1
   C      4
1  A    bar
   B      2
   C      5
2  A    baz
   B      3
   C      6
dtype: object

Desapilamos el dataframe:

In [14]:
df_unstack = df_stack.unstack()
df_unstack

     A  B  C
0  foo  1  4
1  bar  2  5
2  baz  3  6